import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className='py-4 px-4 bg-background bg-[radial-gradient(circle,var(--foreground)_0%,var(--background)_55%);] h-screen'>
        <div className='@container lg:aspect-video mx-auto items-center max-w-[1200px] px-2 border-2 border-foreground rounded-lg overflow-y-scroll shadow-sm shadow-highlight bg-background shd'>
          {children}
        </div>
      </body>
    </html>
  );
}

//  radial-gradient(circle,rgba(31,255,117,1) 0%, rgba(0,0,0,1) 100%);
