import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className='my-2 h-[92%]'>
        <div className='@container lg:aspect-video items-center max-w-[1200px] px-2 mx-1 lg:mx-auto border-2 border-foreground rounded-lg my-4 overflow-y-auto lg:shadow-md shadow-white overflow-x-clip'>
          {children}
        </div>
      </body>
    </html>
  );
}
